spring:
  application:
    name: cleancode
  datasource:
      url: jdbc:h2:mem:cleancode_db
      username: sa
      password: 
      driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect		
